### PR TITLE
calcloud-240 canceled jobs send error message

### PR DESCRIPTION
**Pull request by jaytmiller**
Refactors clean-all lambda and adds "rejection" logic to prevent the batch fail events from 
being processed on all strings.

Extensive refactor of clean lambda to cancel-all based on killable job ids
only, no longer based on ipppssoot control file.  This avoids competing job
kills between job_id-based (required to kill orphan jobs) and
ipppssoot-based (mentioned in control file) and also preserves completed
jobs.

Refactored lambda environments to largely use local.common_env_vars ensuring that BUCKET
is defined in all lambdas.

Added "rejection logic" to kill the batch event handler when the bucket obtained from
the failed job does not match the BUCKET the lambda  was built with.  This stops the
cross-environment event contamination where a secondary environment was processing the
same failure events as the development environment resulting in extraneous error
messages.

Improve signature and documentation for S3Io.put and MessageIo.put, adding the
simple/natural forms S3Io.put(msg_type, payload) and MessageIo.put(msg_type,
payload).  Make signatures of super and subclass put() comply with Liskov
Substitution Principle.

Added payloads to error/terminate messages to indicate which lambda they came from.

### CODE REVIEW

**Review by alphasentaurii — COMMENTED** [review]
Was deleting remote_state.tf intentional? This tells terraform to initialize using a backend remote state instead of local.

**Comment by jaytmiller** [comment]
Nope,  not intentional,  I'll add it back

**Comment by jaytmiller** [comment]
Remote state is back.  Thanks!

**Review by alphasentaurii — APPROVED** [review]
Works as expected on my end (just completed testing in sandbox for cancel-ipst and cancel-all).

**Review by bhayden53 — APPROVED** [review]

**Pull request merged**
